//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEstacionamentoEntities : DbContext
    {
        public dbEstacionamentoEntities()
            : base("name=dbEstacionamentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<TicketVaga> TicketVaga { get; set; }
        public virtual DbSet<Vaga> Vaga { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
    }
}
