//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketVaga
    {
        public int TICKID { get; set; }
        public Nullable<int> VAIID { get; set; }
        public Nullable<int> VEIID { get; set; }
        public Nullable<System.DateTime> DATAHORAENTRADA { get; set; }
        public Nullable<System.DateTime> DATAHORASAIDA { get; set; }
    }
}
