//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int VEIID { get; set; }
        public string VEIPLACA { get; set; }
        public string COR { get; set; }
        public int MARID { get; set; }
    
        public virtual Marca Marca { get; set; }
    }
}
